apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-assistant
spec:
  replicas: 2  # Number of instances
  selector:
    matchLabels:
      app: voice-assistant
  template:
    metadata:
      labels:
        app: voice-assistant
    spec:
      containers:
      - name: voice-assistant
        image: riyasina2024/voice-assistant:latest  # Replace with your image
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: voice-assistant-service
spec:
  type: LoadBalancer  # Use NodePort for Minikube
  selector:
    app: voice-assistant
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
